[package]
name = "nffs_info"
version = "0.1.0"
authors = ["Fabio Utzig <utzig@apache.org>"]
edition = "2018"
description = "An NFFS filesystem analyzer."

[dependencies]
crc16 = "0.4.0"
lazy_static = "1.3.0"
